version: '3.3'

services:
  nginx:
    image: nginx
    ports:
       - "8080:80"
       - "443:443"
  mariadb:
    image: mariadb:10.3
    volumes:
        - mariadb:/var/lib/mariadb
    environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: "no"
        MYSQL_ROOT_PASSWORD: "RenaudLeSang!"
        MYSQL_USER: 'bemoreau'
        MYSQL_PASSWORD: 'bemorenaud'
        MYSQL_DATABASE: 'testdb'
    ports:
        - 3306:3306
  wordpress:
    depends_on:
      - mariadb
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
volumes:
     db_data: {}
     mariadb: