version: '3.3'

services:
  mariadb:
    build:
      context: ./srcs
      dockerfile: ./mariadb/Dockerfile
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: "RenaudLeSang!"
      MYSQL_USER: 'bemoreau'
      MYSQL_PASSWORD: 'bemorenaud'
      MYSQL_DATABASE: 'testdb'
    volumes:
        - mariadb:/var/lib/mariadb
  nginx:
    depends_on:
      - wordpress
    build:
      context: ./srcs/nginx
    ports:
       - "443:443"
  wordpress:
    depends_on:
      - mariadb
    build:
      context: ./srcs
      dockerfile: ./wordpress/Dockerfile
    ports:
      - 3306:3306
    restart: always
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
volumes:
     mariadb: