version: '3.3'

services:
  mariadb:
    build:
      context: ./srcs/mariadb
      dockerfile: ./dockerfile
    environment:
      MDB_USR: "${DB_USR}"
      MDB_PWD: "${DB_PWD}"
    networks:
      - my-network
    ports:
       - "3306:3306"
    volumes:
        - ~/data/db:/var/lib/mysql
    restart: always
  nginx:
    depends_on:
      - wordpress
    build:
      context: ./srcs/nginx
      dockerfile: ./Dockerfile
    networks:
      - my-network
    ports:
      - "443:443"
    extra_hosts:
      - "bemoreau.42.fr:127.0.0.1"
    volumes:
      - ~/data/wp:/var/www/inception
    restart: always
  wordpress:
    depends_on:
      - mariadb
    build:
      context: ./srcs/wordpress
      dockerfile: ./Dockerfile
    networks:
      - my-network
    ports:
      - "9000:9000"
    restart: always
    volumes:
      - ~/data/wp:/var/www/inception
    environment:
      MDB_USR: "${DB_USR}"
      MDB_NAME: "${WP_NAME}"
      MDB_PWD: "${DB_PWD}"
      MDB_HOST: "${WP_HOST}"
      ADM_LOG: "${ADMIN_LOGIN}"
      ADM_PASS: "${ADMIN_PASS}"
      USR_LOG: "${USER_LOGIN}"
      USR_PASS: "${USER_PASS}"
networks:
  my-network:
    driver: bridge
volumes:
  mariadb: