version: '3.3'

services:
  mariadb:
    build:
      context: ./srcs/mariadb
      dockerfile: ./dockerfile
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: "RenaudLeSang!"
      MYSQL_USER: 'bemoreau'
      MYSQL_PASSWORD: 'bemorenaud'
      MYSQL_DATABASE: 'testdb'
      MARIA_LOGIN: "Ben"
      MARIA_PASS: "jamin"
    networks:
      - my-network
    ports:
       - "3306:3306"
    volumes:
        - ~/data/db:/var/lib/mysql
    restart: always
  nginx:
    depends_on:
      - wordpress
    build:
      context: ./srcs/nginx
      dockerfile: ./Dockerfile
    networks:
      - my-network
    ports:
      - "443:443"
      - "80:80" #A remove apres le dn (login.42.fr) car on redirige en https. Uniquement sur les dn
    volumes:
      - ~/data/wp:/var/www/inception
  wordpress:
    depends_on:
      - mariadb
    build:
      context: ./srcs/wordpress
      dockerfile: ./Dockerfile
    networks:
      - my-network
    ports:
      - "9000:9000"
    restart: always
    volumes:
      - ~/data/wp:/var/www/inception
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
networks:
  my-network:
    driver: bridge
volumes:
  mariadb: