FROM alpine

RUN apk update\
    && apk add mysql mysql-client \
    && mkdir /run/mysqld

COPY srcs/config.sql /tmp/config.sql

COPY srcs/init.sql /tmp/init.sql

COPY srcs/my.cnf /etc/my.cnf

COPY srcs/script.sh /

RUN chmod u+x script.sh

ENTRYPOINT ./script.sh

VOLUME /var/lib/mysql

EXPOSE 3306
