FROM alpine

RUN apk update\
	&& apk add mysql mysql-client \
	&& mkdir /run/mysqld

COPY mariadb/srcs/config.sql /tmp/config.sql

COPY mariadb/srcs/init.sql /tmp/init.sql

COPY mariadb/srcs/my.cnf /etc/my.cnf

COPY mariadb/srcs/script.sh /

RUN chmod u+x script.sh

ENTRYPOINT ./script.sh

VOLUME /var/lib/mysql

EXPOSE 3306
