FROM alpine

EXPOSE 8086

COPY srcs/telegraf.conf /etc/telegraf/telegraf.conf

VOLUME /var/lib/influxdb

RUN apk update\
    && apk add influxdb telegraf

ENTRYPOINT telegraf & influxd run -config /etc/influxdb.conf

