FROM alpine

EXPOSE 3000

COPY srcs/telegraf.conf /etc/telegraf/telegraf.conf

RUN mkdir -p /grafana \
	&& apk add --no-cache libc6-compat telegraf\
	&& wget -q -O - https://dl.grafana.com/oss/release/grafana-7.3.6.linux-amd64.tar.gz \
			| tar -xz -C grafana --strip-components=1

COPY srcs/grafana.db /grafana/data/grafana.db

ENTRYPOINT telegraf & grafana/bin/grafana-server -homepath=/grafana 
