FROM debian:buster

RUN apt update -y

RUN apt install mariadb-server -y

COPY ./srcs/script.sh /

COPY srcs/50-server.cnf /etc/mysql/mariadb.conf.d/ 

RUN chmod +x /script.sh

EXPOSE 3306

ENTRYPOINT /script.sh