FROM alpine:latest

EXPOSE 80

RUN apk update

RUN apk add nginx openssl telegraf

RUN adduser -D -g 'www' www

RUN mkdir /www &&\
	chown -R www:www /var/lib/nginx &&\
	chown -R www:www /www

RUN mkdir /etc/nginx/ssl\
	&& openssl req -batch -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/nginx/ssl/nginx.key -out /etc/nginx/ssl/nginx.crt

COPY srcs/nginx.conf /etc/nginx/nginx.conf

COPY srcs/telegraf.conf /etc/telegraf/telegraf.conf

COPY srcs/index.html /www/index.html

RUN mkdir /run/nginx

ENTRYPOINT telegraf & nginx -g "daemon off;"
